"""Transparent feature boundary for the reproducible PTL benchmark model."""
from datetime import date
VEHICLE={"Tata Ace":750,"Pickup":1500,"14ft Truck":3500,"19ft Truck":7000,"32ft MXL":16000}
PRODUCT={"General":1,"FMCG":1.05,"Electronics":1.12,"Pharma":1.18,"Perishable":1.22,"Industrial":1.08,"Fragile":1.14,"High-value":1.20,"Hazard-sensitive":1.16}
SLA={"Standard":1,"Express":1.14,"Critical":1.28}; LOYALTY={"New":1,"Regular":.97,"Strategic":.92}; SECURITY={"Normal":0,"Elevated":1,"High":2}; INSURANCE={"Basic":0,"Enhanced":1,"Full":2}
FEATURES=["distance_km","weight_kg","capacity_kg","utilization","vehicle_code","product_risk","sla_factor","loyalty_factor","seasonal_factor","festival_pressure","fuel_index","toll_inr","labour_index","demand_index","weather_risk","calamity_risk","security_risk","insurance_factor","regulatory_index","geopolitical_index","transit_hours"]
FACTOR_METADATA=[
("Seasonal Impact: Climatic Influences","weather_risk","LIVE_OR_FALLBACK",True,"Open-Meteo current conditions; deterministic fallback disclosed"),("Seasonal Impact: Natural Calamities","calamity_risk","DERIVED",True,"Weather-severity-derived risk; not a disaster-event feed"),("Seasonal Impact: Festivals","festival_pressure","DERIVED",True,"Deterministic Indian festival-window calendar"),("Fuel Cost","fuel_index","BENCHMARK",True,"Configurable neutral benchmark index; no fuel-price feed"),("Distance","distance_km","LIVE_OR_DERIVED",True,"OSRM route distance; labelled Haversine fallback"),("Vehicle Type/Capacity","capacity_kg","BUSINESS_INPUT",True,"Selected vehicle mapped to documented capacity bands"),("Toll Charge","toll_inr","DERIVED",True,"Distance-based estimate, not a live toll quote"),("Labor Cost: Wages and Availability","labour_index","BENCHMARK",True,"Configurable neutral labor benchmark"),("Demand","demand_index","BENCHMARK",True,"Festival/season demand proxy, replaceable by authorized TCI demand"),("Customer Loyalty","loyalty_factor","BUSINESS_INPUT",True,"Optional declared customer tier; no customer-history claim"),("Government Regulations","regulatory_index","BUSINESS_INPUT",True,"Configurable compliance index; no live restriction feed"),("Geopolitical Events","geopolitical_index","PRODUCTION_READY",True,"Neutral, replaceable event-risk input; no event feed"),("Transit Time","transit_hours","LIVE_OR_DERIVED",True,"OSRM travel duration; labelled route fallback"),("Nature of Product","product_risk","BUSINESS_INPUT",True,"Selected product category mapped to transparent risk score"),("Security","security_risk","BUSINESS_INPUT",True,"Optional declared security level; no crime-intelligence claim"),("Insurance","insurance_factor","BUSINESS_INPUT",True,"Optional declared cover plus shipment-value band; not an insurer quote")]
def festival_pressure(today=None):
 d=today or date.today();md=(d.month,d.day);windows=[((1,10),(1,18)),((3,5),(3,15)),((8,24),(9,10)),((10,10),(11,12))];return 1.16 if any(a<=md<=b for a,b in windows) else 1.0
def build(req,r,w):
 month=date.today().month;seasonal=1.12 if month in (9,10,11,12) else 1.06 if month in (6,7,8) else .98;cap=VEHICLE[req.vehicle_type];risk={"Low":0,"Moderate":1,"High":2}[w['risk']];festival=festival_pressure();security=SECURITY[req.security_level] if req.security_level else (1 if req.product_category in ('Electronics','Pharma','High-value') else 0);insurance=INSURANCE[req.insurance_option] if req.insurance_option else 0
 return {"distance_km":r['distance_km'],"weight_kg":req.weight_kg,"capacity_kg":cap,"utilization":min(req.weight_kg/cap,1.5),"vehicle_code":list(VEHICLE).index(req.vehicle_type),"product_risk":PRODUCT[req.product_category],"sla_factor":SLA[req.sla],"loyalty_factor":LOYALTY[req.customer_loyalty],"seasonal_factor":seasonal,"festival_pressure":festival,"fuel_index":req.fuel_cost_index or 1,"toll_inr":r['distance_km']*.75,"labour_index":req.labour_cost_index or 1,"demand_index":max(seasonal,festival),"weather_risk":risk,"calamity_risk":risk if risk==2 else 0,"security_risk":security,"insurance_factor":insurance+(1 if (req.shipment_value_inr or 0)>=100000 else 0),"regulatory_index":req.regulatory_impact_index or 1,"geopolitical_index":req.geopolitical_risk_index or 1,"transit_hours":r['travel_hours']}
def factor_summary(features,r,w):
 weather_source='LIVE' if w['source']=='Open-Meteo' else 'DERIVED';route_source='LIVE' if r['source']=='OSRM' else 'DERIVED';out=[]
 for name,feature,kind,ml,method in FACTOR_METADATA:
  source=weather_source if kind=='LIVE_OR_FALLBACK' else route_source if kind=='LIVE_OR_DERIVED' else kind;out.append({'factor':name,'feature':feature,'value':features.get(feature),'source_type':source,'affects_ml':ml,'affects_alerts':feature in {'weather_risk','calamity_risk','festival_pressure','demand_index','security_risk','regulatory_index','insurance_factor','transit_hours','utilization'},'method':method})
 return out
